cargo-features = ["edition2024"]
[package]
name = "silver_legion"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_yaml = "0.9"
